# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'yourACRName'
  repositoryName: 'yourRepositoryName'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

stages:
- stage: Build
  jobs:
  - job: MavenBuild
    displayName: 'Build Java App with Maven'
    steps:
    - task: UseJavaVersion@1
      inputs:
        versionSpec: '11'
        addToPath: true

    - script: 'mvn clean install'
      displayName: 'Maven Build'

- stage: BuildDockerImage
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Image'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(acrName)/$(repositoryName):$(Build.BuildId)

- stage: PushToACR
  jobs:
  - job: PushToACR
    displayName: 'Push Docker Image to ACR'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - task: Docker@2
      inputs:
        command: 'push'
        containerRegistry: '$(acrName)'
        repository: '$(repositoryName)'
        tags: |
          $(Build.BuildId)

