apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsj-deployment
spec:
  selector:
    matchLabels:
      app: hsj
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hsj
    spec:
      containers:
      - name: hsj
        image: hsj89/webapp:version-26
        ports:
        - containerPort: 8080