apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1  # Number of desired pods
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-container
        image: hsjacr.azurecr.io/samplewar:$(ImageTag)  #Replace with your Docker image details
        env:
        - name: BUILD_ID
          value: "$(Build.BuildId)"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80  # Expose the application on port 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 80  # Pod port
  type: LoadBalancer  # Use LoadBalancer type for external access
